services: 
  laravel: 
    build: .
    working_dir: /app
    volumes: 
      - .:/app
    ports: 
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    networks: 
      - akiba_network
    command: php artisan serve --host=0.0.0.0 --port=8000
    container_name: akiba_laravel

  node: 
    image: node:22
    working_dir: /app
    volumes: 
      - .:/app
    ports: 
      - "5173:5173"
    networks: 
      - akiba_network 
    command: npm run dev -- --host 0.0.0.0
    container_name: akiba_node 

  mysql: 
    image: mysql:8
    ports: 
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: "root"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - akiba_network
    container_name: akiba_mysql 

  phpmyadmin: 
    image: phpmyadmin/phpmyadmin
    ports: 
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on: 
      - mysql
    networks: 
      - akiba_network
    container_name: akiba_phpmyadmin 

volumes:
  mysql_data:
  
networks: 
  akiba_network:
