name: Question
description: Ask a question about the project.
title: "[QUESTION] "
labels:
  - question

body:
  - type: textarea
    id: question
    attributes:
      label: What is your question?
      description: Write your question clearly and directly.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context (optional)
      description: Add any context that helps understand your question.
    validations:
      required: false